### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by TimoBolkart** [luckycallor/InsightFace-tensorflow#1]
Is there any possibility to access the pre-trained models without installing Baidu software?

**Comment by luckycallor** [comment]
As this is required by Baidu, I am afraid that you might install Baidu software to access the pre-trained models, currently.
I will try to find other free way to share the pretrained models, or do you have any advice?

**Comment by luckycallor** [comment]
@TimoBolkart 
I have added a google drive link for the best pretrained model.

**Comment by TimoBolkart** [comment]
@luckycallor great, thank you.
