### ISSUE TITLE
About image normalization

### ISSUE THREAD

**Issue by yinguobing** [luckycallor/InsightFace-tensorflow#4]
Hi, luckycallor,

ArcFace论文中对图像的归一化是这样描述的：
> The faces are cropped and resized to 112 × 112, and each pixel (ranged between [0, 255]) in RGB images is normalised by subtracting 127.5 then divided by 128.

在您的实现中是这样的：
https://github.com/luckycallor/InsightFace-tensorflow/blob/3eca399039a0b2ca305d908960d90a96a0ea9c1c/get_embd.py#L41

这两种做法的区别是归一化后的极值范围。不知道您这样做是否是因为有更好的表现？

**Comment by luckycallor** [comment]
@yinguobing 
你好，感谢您对论文和代码的仔细阅读，我这里的归一化方式是采用的计算机视觉中的常用做法。虽然与原论文的方法有略微不同，但我认为这对模型精度影响应该不大。

**Comment by yinguobing** [comment]
收到，多谢解答 :+1:
