### ISSUE TITLE
questins about training time

### ISSUE THREAD

**Issue by friedhelm739** [luckycallor/InsightFace-tensorflow#6]
I use Resnet_50 to train ,batch_size 256, gpu 2*1080ti,however,I found that it spent nealy 12 seconds to train only one time, how could it so slow?did anyone know that?

**Comment by luckycallor** [comment]
@friedhelm739 
12 seconds per step is really too long. In my experiments with modified ResNet_v2-50, batch size 100, gpu 1*1080Ti, it costs around 1 second per step. Following points you may check:
1. image size is 112*112 in my experiment
2. use tfrecord to accelerate image reading speed
3. check whether your GPU is running with full power

**Comment by friedhelm739** [comment]
@luckycallor 
I found that it`s the wrong setting of my conda .After fixing ,it costs nearly  50 seconds per 100 times by using 2*1080ti in 256 batch size,thank you for your reference data~

**Comment by clhne** [comment]
> @luckycallor
> I found that it`s the wrong setting of my conda .After fixing ,it costs nearly 50 seconds per 100 times by using 2*1080ti in 256 batch size,thank you for your reference data~
@friedhelm739 @luckycallor 
请问：
wrong setting 是怎么修改好的呢？
我这边发现batch_size设置为126
当使用2*2080Ti时为0.21s/step
当使用6*2080Ti时为0.86s/step
速度反而成倍下降？

**Comment by friedhelm739** [comment]
@clhne 
抱歉，我的conda是下载不了gpu版tensorflow运行，手动下载安装后就可以了。
你可以打印一下每个gpu运行通道的时间，还有合并时间等，看一看时间主要花在哪里了
这个仓库的代码是同步运行的，兴许是其中一块gpu出了问题，你可以尝试打印时间
